### ISSUE TITLE
This repo has been excluded from Hackatoberfest

### ISSUE THREAD

**Issue by nenodias** [mirllamarques/Deep-Web-HacktoberFest-2021#71]
This repo has been excluded from Hackatoberfest
![image](https://user-images.githubusercontent.com/3880625/136597480-d060a37b-3956-4fcf-be53-494f3f47050c.png)

**Comment by nenodias** [comment]
Tranquilo, só achei válido te avisar.

**Comment by mirllamarques** [comment]
Obrigada, ainda não tava sabendo da denúncia
